"""Initial Quiteno Schema

Revision ID: 6087f2602bb5
Revises: 
Create Date: 2026-03-28 13:19:18.462486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6087f2602bb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('examples', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('examples_word_id_fkey'), 'examples', type_='foreignkey')
    op.create_foreign_key(None, 'examples', 'words', ['word_id'], ['id'])
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('quiz_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quiz_questions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('votes', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('words', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('words', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('words', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('words_slug_key'), 'words', type_='unique')
    op.drop_constraint(op.f('words_term_key'), 'words', type_='unique')
    op.create_index(op.f('ix_words_slug'), 'words', ['slug'], unique=True)
    op.create_index(op.f('ix_words_term'), 'words', ['term'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_term'), table_name='words')
    op.drop_index(op.f('ix_words_slug'), table_name='words')
    op.create_unique_constraint(op.f('words_term_key'), 'words', ['term'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('words_slug_key'), 'words', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('words', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('words', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('words', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('votes', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('quiz_questions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('quiz_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'examples', type_='foreignkey')
    op.create_foreign_key(op.f('examples_word_id_fkey'), 'examples', 'words', ['word_id'], ['id'], ondelete='CASCADE')
    op.alter_column('examples', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
